name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/rocker-org/tidyverse:4.5
    strategy:
      fail-fast: false

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: 1.4.515

    - name: Hello world
      run: |
        Rscript -e 'print("Hello world")'
